### ISSUE TITLE
Add the ability for the service to parse YAML files

### ISSUE THREAD

**Issue by vukani-dev** [vukani-dev/improvement-roll-service#1]
Right now the service parses **JSON** files in the categories directory into a SharedCategory struct.
Add the ability to do the same with **YAML** files.

This can be updated in the **parseCategory** function on line 219.
Simply check if it is a **YAML** file and if so read the file and parse it into the appropriate struct to return.

**Comment by krishnaindani** [comment]
hey, could I work on this? Would like to try it.

**Comment by vukani-dev** [comment]
> hey, could I work on this? Would like to try it.

Absolutely its all yours!! Lmk if you have any questions,

**Comment by arshad-k7** [comment]
Can i contribute into this?

**Comment by vukani-dev** [comment]
> Can i contribute into this?

I also just made another enhancement of the same kind if you are interested here:  #2

**Comment by arshad-k7** [comment]
> > Can i contribute into this?
> 
> I also just made another enhancement of the same kind if you are interested here: #2

sure, thanks
