### ISSUE TITLE
Add the ability for the service to parse TOML files

### ISSUE THREAD

**Issue by vukani-dev** [vukani-dev/improvement-roll-service#2]
Right now the service parses JSON files in the categories directory into a SharedCategory struct.
Add the ability to do the same with `TOML` files.

This can be updated in the parseCategory function on line 219.
Simply check if it is a `TOML` file and if so read the file and parse it into the appropriate struct to return.

The struct to parse it to has the following:
- Tags : array of strings
- Author : string
- Date : string of datetime in RFC-3339 format
- Category ( [here](https://github.com/vukani-dev/improvement-roll/blob/main/categories/examples/test.toml) is an example of a valid toml Category)

**Comment by arshad-k7** [comment]
please provide the write access to push PR

**Comment by arshad-k7** [comment]
Please look into my PR https://github.com/vukani-dev/improvement-roll-service/pulls

**Comment by vukani-dev** [comment]
Looks great! Thank you!
