### ISSUE TITLE
Update parser to accept date in MM-DD-YYYY format rather than RFC-3339

### ISSUE THREAD

**Issue by vukani-dev** [vukani-dev/improvement-roll-service#4]
Right now, the Unmarshal function for JSON and TOML parsing require a datetime in RFC-3339 format.
We should update this to accept a datetime in MM-DD-YYYY format.

That way a file can be read in with date = "10-05-2022" and be parsed correctly into a `time.Time` type under SharedCategory

**Comment by abjklk** [comment]
Hello @vukani-dev I can take this up, can you assign this issue to me ?

**Comment by vukani-dev** [comment]
> Hello @vukani-dev I can take this up, can you assign this issue to me ?

Sure can!

**Comment by arshad-k7** [comment]
Please check my PR
